// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Entities.Article", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryId = 1,
                            Content = "AspNet Core Deneme Makalesi Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget posuere magna. Phasellus pulvinar ultrices maximus. Maecenas non porta ligula. In ac dui sollicitudin, elementum felis vitae, viverra diam. Donec ut dolor eu dolor mattis tristique. Sed commodo eu justo rutrum condimentum. Sed dolor tellus, bibendum sit amet erat ac, auctor facilisis nulla. Mauris feugiat enim sed eros tincidunt, a finibus ex iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam mattis sit amet tellus at placerat. Nulla sagittis condimentum tortor, tincidunt tincidunt erat dictum at. Cras sit amet mi leo. Sed eu risus cursus, congue metus eu, convallis ante. Maecenas ac luctus tellus, a iaculis velit. Vestibulum porta accumsan nulla, ut ultricies neque pellentesque vitae. Duis nisl tellus, interdum vel rhoncus in, condimentum quis erat.\r\n\r\nQuisque vitae porta metus. Integer laoreet porta ligula vitae pharetra. Donec pharetra, ipsum in pellentesque auctor, urna turpis feugiat erat, non aliquam lacus odio id nunc. Curabitur porta in lacus id blandit. Nullam lorem dolor, lacinia in varius sed, consequat sollicitudin urna. Nulla facilisi",
                            CreatedDate = new DateTime(2023, 3, 8, 15, 54, 53, 61, DateTimeKind.Local).AddTicks(3472),
                            ImageId = 1,
                            IsDeleted = false,
                            Title = "AspNet Core Deneme Makalesi",
                            ViewCount = 0
                        },
                        new
                        {
                            ID = 2,
                            CategoryId = 2,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget posuere magna. Phasellus pulvinar ultrices maximus. Maecenas non porta ligula. In ac dui sollicitudin, elementum felis vitae, viverra diam. Donec ut dolor eu dolor mattis tristique. Sed commodo eu justo rutrum condimentum. Sed dolor tellus, bibendum sit amet erat ac, auctor facilisis nulla. Mauris feugiat enim sed eros tincidunt, a finibus ex iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam mattis sit amet tellus at placerat. Nulla sagittis condimentum tortor, tincidunt tincidunt erat dictum at. Cras sit amet mi leo. Sed eu risus cursus, congue metus eu, convallis ante. Maecenas ac luctus tellus, a iaculis velit. Vestibulum porta accumsan nulla, ut ultricies neque pellentesque vitae. Duis nisl tellus, interdum vel rhoncus in, condimentum quis erat.\r\n\r\nQuisque vitae porta metus. Integer laoreet porta ligula vitae pharetra. Donec pharetra, ipsum in pellentesque auctor, urna turpis feugiat erat, non aliquam lacus odio id nunc. Curabitur porta in lacus id blandit. Nullam lorem dolor, lacinia in varius sed, consequat sollicitudin urna. Nulla facilisi",
                            CreatedDate = new DateTime(2023, 3, 8, 15, 54, 53, 61, DateTimeKind.Local).AddTicks(3475),
                            ImageId = 2,
                            IsDeleted = false,
                            Title = "Redis Deneme Makalesi",
                            ViewCount = 0
                        },
                        new
                        {
                            ID = 3,
                            CategoryId = 3,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget posuere magna. Phasellus pulvinar ultrices maximus. Maecenas non porta ligula. In ac dui sollicitudin, elementum felis vitae, viverra diam. Donec ut dolor eu dolor mattis tristique. Sed commodo eu justo rutrum condimentum. Sed dolor tellus, bibendum sit amet erat ac, auctor facilisis nulla. Mauris feugiat enim sed eros tincidunt, a finibus ex iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam mattis sit amet tellus at placerat. Nulla sagittis condimentum tortor, tincidunt tincidunt erat dictum at. Cras sit amet mi leo. Sed eu risus cursus, congue metus eu, convallis ante. Maecenas ac luctus tellus, a iaculis velit. Vestibulum porta accumsan nulla, ut ultricies neque pellentesque vitae. Duis nisl tellus, interdum vel rhoncus in, condimentum quis erat.\r\n\r\nQuisque vitae porta metus. Integer laoreet porta ligula vitae pharetra. Donec pharetra, ipsum in pellentesque auctor, urna turpis feugiat erat, non aliquam lacus odio id nunc. Curabitur porta in lacus id blandit. Nullam lorem dolor, lacinia in varius sed, consequat sollicitudin urna. Nulla facilisi",
                            CreatedDate = new DateTime(2023, 3, 8, 15, 54, 53, 61, DateTimeKind.Local).AddTicks(3477),
                            ImageId = 3,
                            IsDeleted = false,
                            Title = "Docker Deneme Makalesi",
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("Model.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2023, 3, 8, 15, 54, 53, 61, DateTimeKind.Local).AddTicks(3184),
                            IsDeleted = false,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2023, 3, 8, 15, 54, 53, 61, DateTimeKind.Local).AddTicks(3186),
                            IsDeleted = false,
                            Name = "Redis"
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2023, 3, 8, 15, 54, 53, 61, DateTimeKind.Local).AddTicks(3188),
                            IsDeleted = false,
                            Name = "Docker"
                        });
                });

            modelBuilder.Entity("Model.Entities.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2023, 3, 8, 15, 54, 53, 61, DateTimeKind.Local).AddTicks(3539),
                            FileName = "ASP.NET Core Image",
                            FileType = "Jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2023, 3, 8, 15, 54, 53, 61, DateTimeKind.Local).AddTicks(3541),
                            FileName = "Redis Deneme Makalesi",
                            FileType = "png",
                            IsDeleted = false
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2023, 3, 8, 15, 54, 53, 61, DateTimeKind.Local).AddTicks(3542),
                            FileName = "Docker Deneme Makalesi",
                            FileType = "png",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Model.Entities.Article", b =>
                {
                    b.HasOne("Model.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Image", "Image")
                        .WithMany("Articles")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Model.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Model.Entities.Image", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
